### ISSUE TITLE
Quotes around message

### ISSUE THREAD

**Issue by PBahner** [PBahner/Serial-Monitor#1]
When receiving serial data the message is in quotes and b.
For example:
`b'serial-message'`
Remove b and the quotes!

**Comment by SecretJuice** [comment]
I faced a similar issue when I was working on an Arduino project recently.

It seems like the 'b' indicates that the data is in a byte format, so we use .decode('utf-8') to make it a normal string. Then to get rid of dangling escape characters, we use .strip().

This is my first contribution to a public project. Hopefully it was helpful!

#2
